/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125748-g80eb9e99b9-20260723"
#endif /* AVUTIL_FFVERSION_H */
